version: "1.0"
services:
  frontend:
    build: ./front
    depends_on:
      - backend
    ports:
      - "3002:3000"
    networks:
      - search-for-kits-network
  backend:
    build: ./back
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks: 
     - search-for-kits-network

  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
      MOGODB_INITDB_DATABASE: analytics
    ports:
      - "27017:27017"
    networks: 
     - search-for-kits-network

networks:
  search-for-kits-network:

volumes: 
  mongodb_data: